### ISSUE TITLE
Link to https://talk.libre.solar/ is broken 

### ISSUE THREAD

**Issue by bjoerns1983** [LibreSolar/libresolar.github.io#22]
Just wanted to inform you that the link to https://talk.libre.solar/ is broken due a revoked SSL Certificate.

**Comment by martinjaeger** [comment]
Thanks for letting me know.

For some reason it's working fine here. It says the certificate is valid till April 18, 2022. Can you double-check if the issue persists if you reload the page?

**Comment by bjoerns1983** [comment]
Totally strange. I get a SEC_ERROR_REVOKED_CERTIFICATE error with my Firefox 97 on Manjaro as well as on Windows and.
If i use LibreWolf on Manjaro it works without problems like Chrome on Windows.

Seems that this is a Firefox issue.

**Comment by DeeFuse** [comment]
I did some digging an can confirm that the libre.solar subdomains are indeed revoced due to a "bug" in LetsEncrypts ALPN verification process [Details](https://community.letsencrypt.org/t/questions-about-renewing-before-tls-alpn-01-revocations/170449)

MS Edge works as well, IMHO these browser are misbehaving and not blocking / warning a user about the revoked certificate.

A renewal of these certificates will fix the problem.

**Comment by martinjaeger** [comment]
Thanks for following up on this. I have renewed all certificates, so it should work now. Can you confirm?

**Comment by bjoerns1983** [comment]
Works for me now. Thanks!

**Comment by DeeFuse** [comment]
Works for me as well.

**Comment by martinjaeger** [comment]
Thanks. Closing the issue then.
